version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.0
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Force Bundler Version
          command: |
            sudo gem update --system
            gem install bundler
            bundle check || bundle config set --local path 'vendor/bundle' || bundle install --jobs=6 --retry=3
      - run: 
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      
  brakeman:
      executor: ruby/default
      steps:
        - attach_workspace:
            at: ~/
        - run:
            name: Brakeman
            command: bundle exec brakeman

  licensed:
      executor: ruby/default
      steps:
        - attach_workspace:
            at: ~/
        - run: bundle exec licensed cache
        - run: bundle exec licensed status

workflows:
  version: 2
  integration:
    jobs:
      - build
      - brakeman:
          requires:
            - build
      - licensed:
          requires:
            - build
